Repository ISIS3510-Moviles/Flutter, pull requests merged in 2025-05, with the labels that each got.

#63 Feature/notifications screen with Hive
  lib/data/offline/alerts_by_date.dart
  lib/data/offline/alerts_by_date.g.dart
  lib/data/offline/cached_alert.dart
  lib/data/offline/cached_alert.g.dart
  lib/data/offline/reservations_by_date.dart
  lib/domain/entities/alert_entity.dart
  lib/main.dart
  lib/presentation/providers/alerts/alert_provider.dart
  lib/presentation/screens/notifications_screen.dart
Labels: enhancement

#64 feature/offline-search-bar-#190
  .gitignore
  lib/data/offline/food_tag.dart
  lib/presentation/providers/restaurants/restaurants_provider.dart
  lib/presentation/views/home_view.dart
Labels: enhancement

#65 Feature/restaurants by tags #191
  .gitignore
  lib/domain/entities/product_entity.dart
  lib/domain/entities/product_entity.g.dart
  lib/presentation/providers/food-tags/food_tag_provider.dart
  lib/presentation/providers/restaurants/restaurants_provider.dart
  lib/presentation/widgets/shared/sliver_list_food_restaurant.dart
Labels: enhancement

#66 fix/bq-position-in-code-#193
  lib/presentation/views/home_view.dart
Labels: bug

#68 fix/recommenadtions-system-#192
  lib/presentation/views/home_view.dart
  lib/presentation/views/recommendation_view.dart
  pubspec.lock
Labels: bug, enhancement

#67 Fix/fix screens and find bugs #194
  lib/presentation/screens/reservation_screen.dart
  lib/presentation/views/home_view.dart
  lib/presentation/views/restaurant/book_tab.dart
Labels: bug

#70 Fix: import warnings and use of variables #195
  lib/data/datasources/product_backend_datasource.dart
  lib/presentation/screens/restaurant_screen.dart
  lib/presentation/screens/tag_screen.dart
  lib/presentation/views/home_view.dart
  lib/presentation/views/recommendation_view.dart
  lib/presentation/widgets/shared/restaurant_card.dart
Labels: bug

#71 Fix/fix screens and find bugs 2 #194
  lib/data/datasources/reservation_backend_datasource.dart
  lib/data/offline/comment_queue_manager.dart
  lib/data/offline/reservation_queue_manager.dart
  lib/presentation/screens/food_screen.dart
  lib/presentation/screens/restaurant_screen.dart
  lib/presentation/screens/tag_screen.dart
  lib/presentation/views/home_view.dart
  lib/presentation/views/restaurant/book_tab.dart
  lib/presentation/views/restaurant/description_tab.dart
  lib/presentation/widgets/shared/food_card.dart
  lib/services/auth_service.dart
Labels: bug

#72 fix/antipattern-#196
  lib/presentation/screens/restaurant_screen.dart
  pubspec.lock
Labels: bug

#74 feature/isolate-for-desearializa-product-list-#200
  lib/presentation/screens/login_screen.dart
  lib/services/auth_service.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#75 feature/isolates-filters-#199
  ios/Podfile.lock
  lib/presentation/providers/restaurants/restaurants_provider.dart
  lib/presentation/views/home_view.dart
  pubspec.lock
Labels: enhancement

#76 feature/serialize-product-list-into-string-list-isolate-#201
  lib/services/auth_service.dart
Labels: enhancement

#77 feature/enhance-add review-button-#202
  lib/presentation/views/restaurant/reviews_tab.dart
Labels: enhancement

#79 Fix/do-minor-fixes-#204
  lib/data/repositories/alert_repository_impl.dart
  lib/data/repositories/comment_repository_impl.dart
  lib/data/repositories/product_repository_impl.dart
  lib/data/repositories/reservation_repository_impl.dart
  lib/data/repositories/restaurant_repository_impl.dart
  lib/presentation/screens/food_screen.dart
  lib/presentation/screens/restaurant_screen.dart
  lib/presentation/views/recommendation_view.dart
  lib/presentation/widgets/shared/sliver_list_food_restaurant.dart
Labels: bug, enhancement

#82 feature/sort-reviews-#203
  lib/presentation/views/restaurant/reviews_tab.dart
Labels: enhancement

#83 Fix/home-view-merge-#207
  lib/presentation/views/home_view.dart
Labels: bug

#84 Fix/blank-food-tags-#205
  lib/presentation/views/home_view.dart
Labels: bug

#85 feature/restaurant-login-#230
  lib/config/router/app_router.dart
  lib/data/datasources/restaurant_backend_datasource.dart
  lib/data/repositories/restaurant_repository_impl.dart
  lib/domain/datasources/restaurant_datasource.dart
  lib/domain/entities/entities.dart
  lib/domain/entities/product_entity.dart
  lib/domain/repositories/restaurant_repository.dart
  lib/globals/GlobalRestaurant.dart
  lib/presentation/screens/home-screen-restaurant.dart
  lib/presentation/screens/login_screen.dart
  lib/presentation/screens/profile_screen.dart
  lib/presentation/screens/reservation_screen.dart
  lib/presentation/screens/tag_screen.dart
  lib/presentation/views/restaurant/description_tab.dart
  lib/presentation/widgets/shared/custom_bottom_navigation-restaurant.dart
  lib/presentation/widgets/shared/sliver_list_food_restaurant.dart
  lib/services/auth_service.dart
  pubspec.lock
Labels: enhancement

#86 feature/reservations-restaurant-#231
  lib/config/router/app_router.dart
  lib/data/datasources/reservation_backend_datasource.dart
  lib/data/datasources/restaurant_backend_datasource.dart
  lib/data/mappers/reservation_mapper.dart
  lib/data/models/reservation_backend.dart
  lib/data/repositories/reservation_repository_impl.dart
  lib/domain/datasources/reservation_datasource.dart
  lib/domain/entities/reservation_entity.dart
  lib/domain/repositories/reservation_repository.dart
  lib/presentation/providers/reservations/reservation_provider_restaurant.dart
  lib/presentation/screens/login_screen.dart
  lib/presentation/screens/reservation_screen_restaurant.dart
  lib/presentation/widgets/shared/custom_bottom_navigation-restaurant.dart
  lib/presentation/widgets/shared/custom_sliver_appbar_restaurant.dart
  lib/services/auth_service.dart
Labels: enhancement

#87 Feature/edit-information-screen-#217
  lib/config/router/app_router.dart
  lib/presentation/screens/restaurant-info.dart
Labels: enhancement

#88 Feature/functional-edit-information-screen-#242
  lib/data/datasources/restaurant_backend_datasource.dart
  lib/domain/datasources/restaurant_datasource.dart
  lib/presentation/screens/restaurant-info.dart
Labels: enhancement

#89 feature/view-add-products-#232
  lib/config/router/app_router.dart
  lib/presentation/screens/add-product-screen.dart
Labels: enhancement

#93 Feature/implement micro optimizations #211
  analysis_options.yaml
  lib/config/router/app_router.dart
  lib/data/datasources/alert_backend_datasource.dart
  lib/data/datasources/reservation_backend_datasource.dart
  lib/data/mappers/dietary_tag_mapper.dart
  lib/data/mappers/food_tag_mapper.dart
  lib/data/mappers/product_mapper.dart
  lib/data/mappers/restaurant_mapper.dart
  lib/presentation/providers/restaurants/restaurants_provider.dart
  lib/presentation/screens/food_screen.dart
  lib/presentation/screens/login_screen.dart
  lib/presentation/screens/profile_screen.dart
  lib/presentation/screens/reservation_screen.dart
  lib/presentation/screens/reservation_screen_restaurant.dart
  lib/presentation/screens/restaurant-info.dart
  lib/presentation/screens/restaurant_screen.dart
  lib/presentation/screens/tag_screen.dart
  lib/presentation/views/custom_title.dart
  lib/presentation/views/home_view.dart
  lib/presentation/views/recommendation_view.dart
  lib/presentation/views/restaurant/arrive_tab.dart
  lib/presentation/views/restaurant/book_tab.dart
  lib/presentation/views/restaurant/description_tab.dart
  lib/presentation/views/restaurant/food_tab.dart
  lib/presentation/widgets/shared/custom_bottom_navigation.dart
  lib/presentation/widgets/shared/custom_sliver_appbar.dart
  lib/presentation/widgets/shared/custom_sliver_appbar_restaurant.dart
  lib/presentation/widgets/shared/food_card.dart
  lib/presentation/widgets/shared/restaurant_card.dart
  lib/services/auth_service.dart
  lib/services/restaurant_cache_service.dart
Labels: enhancement

#94 feature/merge-fix-252
  .gitignore
  android/app/google-services.json
  lib/presentation/widgets/shared/custom_sliver_appbar_restaurant.dart
Labels: bug

#98 Feature/implement-business-question-9-#210
  lib/config/router/app_router.dart
Labels: enhancement

#102 feature/bussines-question-16-#234
  google-services.json
  lib/presentation/views/home_view.dart
  lib/presentation/views/recommendation_view.dart
  lib/presentation/views/restaurant/book_tab.dart
  lib/presentation/widgets/shared/restaurant_card.dart
Labels: enhancement
